spring:
  port: ${SERVER_PORT:8080}
  datasource:
    url: jdbc:h2:file:/data/database
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yml
    enabled: true

logging:
  level:
    org.springframework.boot.context.properties: INFO

mybatis:
  mapper-locations: classpath:mapper/**/*.xml

riot:
  url: ${BASE_RIOT_PATH:https://europe.api.riotgames.com/}
  api:
    token: ${API_TOKEN}

lol:
  url: ${BASE_RIOT_PATH:https://europe.api.riotgames.com/}